services:
  frontend:
    build:
      context: ./policy-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./policy-app:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build:
      context: ./policy-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./policy-backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  default:
    driver: bridge